import {
  Armchair,
  Crown,
  Flower2,
  LayoutGrid,
  ScanSearch,
  Sofa,
  Sparkles,
  SquareStack,
  Ticket,
  Waves,
} from "lucide-react";
import {
  type PlannerItem,
  type PlannerPlacedItemsByPreset,
  type PlannerPreset,
} from "@/components/planner/planner-types";

export const PLANNER_PRESETS: PlannerPreset[] = [
  {
    description: "Balanced dining layout with a clear aisle to the stage and front seating.",
    id: "reception",
    label: "Reception layout",
  },
  {
    description: "More open central floor for ceremony movement and family photo moments.",
    id: "ceremony",
    label: "Ceremony layout",
  },
  {
    description: "Presentation-focused layout for launches, briefings, and appreciation nights.",
    id: "corporate",
    label: "Corporate layout",
  },
] as const;

export const PLANNER_ITEMS: PlannerItem[] = [
  {
    category: "furniture",
    color: "#cbd5e1",
    depth: 50,
    height: 48,
    icon: SquareStack,
    id: "stage",
    label: "Stage",
    meshHeight: 16,
    note: "Use this as the focal point for ceremonies, speeches, or pelamin placement.",
    shape: "rectangle",
    width: 92,
    zoneHint: "Main stage",
  },
  {
    category: "furniture",
    color: "#e2e8f0",
    depth: 40,
    height: 40,
    icon: LayoutGrid,
    id: "round-table",
    label: "Round Table",
    meshHeight: 24,
    note: "Best for dining zones and group seating throughout the hall.",
    shape: "circle",
    width: 40,
    zoneHint: "Dining area",
  },
  {
    category: "furniture",
    color: "#e2e8f0",
    depth: 30,
    height: 28,
    icon: LayoutGrid,
    id: "rect-table",
    label: "Rect Table",
    meshHeight: 20,
    note: "Useful for buffet lines, registration, or long presentation tables.",
    shape: "rectangle",
    width: 72,
    zoneHint: "Service area",
  },
  {
    category: "furniture",
    color: "#94a3b8",
    depth: 20,
    height: 20,
    icon: Armchair,
    id: "chair",
    label: "Chair",
    meshHeight: 28,
    note: "Adds focused seating near the stage or along the aisle.",
    shape: "circle",
    width: 20,
    zoneHint: "Guest seating",
  },
  {
    category: "furniture",
    color: "#b58ae0",
    depth: 26,
    height: 26,
    icon: Crown,
    id: "ornate-chair",
    label: "Ornate Chair",
    meshHeight: 40,
    note: "A premium accent chair for solemnisation, pelamin styling, or VIP photo moments.",
    shape: "rectangle",
    width: 26,
    zoneHint: "Premium seating",
  },
  {
    category: "furniture",
    color: "#f87171",
    depth: 30,
    height: 28,
    icon: Sofa,
    id: "vip-sofa",
    label: "VIP Sofa",
    meshHeight: 22,
    note: "Ideal for family or VVIP seating close to the main focus area.",
    shape: "rectangle",
    width: 64,
    zoneHint: "Front seating",
  },
  {
    category: "furniture",
    color: "#60a5fa",
    depth: 30,
    height: 28,
    icon: Ticket,
    id: "registration",
    label: "Registration",
    meshHeight: 20,
    note: "Helps define guest arrival and registration flow near the entrance.",
    shape: "rectangle",
    width: 60,
    zoneHint: "Entrance",
  },
  {
    category: "decor",
    color: "#ef4444",
    depth: 140,
    height: 120,
    icon: Waves,
    id: "aisle",
    label: "Aisle Carpet",
    meshHeight: 1,
    note: "Creates a stronger processional path towards the stage or centre aisle.",
    shape: "rectangle",
    width: 24,
    zoneHint: "Centre aisle",
  },
  {
    category: "decor",
    color: "#d9c2a3",
    depth: 62,
    height: 36,
    icon: Sparkles,
    id: "pelamin",
    label: "Pelamin",
    meshHeight: 56,
    note: "A decorative pelamin focal point for solemnisation and reception backdrops.",
    shape: "rectangle",
    width: 74,
    zoneHint: "Main stage",
  },
  {
    category: "decor",
    color: "#34d399",
    depth: 24,
    height: 24,
    icon: Flower2,
    id: "floral",
    label: "Floral Stand",
    meshHeight: 42,
    note: "Works well for framing entrances, stages, and photo corners.",
    shape: "circle",
    width: 24,
    zoneHint: "Decor points",
  },
  {
    category: "decor",
    color: "#c084fc",
    depth: 44,
    height: 44,
    icon: ScanSearch,
    id: "photo-booth",
    label: "Photo Booth",
    meshHeight: 58,
    note: "Reserve a dedicated corner for guest portraits and event photography.",
    shape: "rectangle",
    width: 50,
    zoneHint: "Photo corner",
  },
] as const;

export const PRESET_PLACED_ITEMS: PlannerPlacedItemsByPreset = {
  ceremony: [
    { id: "c-1", itemId: "pelamin", label: "Ceremony pelamin", rotation: 0, widthClass: "w-28", x: 67, y: 18, zone: "Main stage" },
    { id: "c-2", itemId: "aisle", label: "Main aisle", rotation: 0, widthClass: "w-10", x: 45, y: 42, zone: "Centre aisle" },
    { id: "c-3", itemId: "ornate-chair", label: "Ceremony accent chair", rotation: 0, widthClass: "w-24", x: 33, y: 24, zone: "Premium seating" },
    { id: "c-4", itemId: "floral", label: "Floral pair", rotation: 0, widthClass: "w-12", x: 73, y: 56, zone: "Decor points" },
  ],
  corporate: [
    { id: "corp-1", itemId: "stage", label: "Presentation stage", rotation: 0, widthClass: "w-28", x: 67, y: 18, zone: "Main stage" },
    { id: "corp-2", itemId: "rect-table", label: "Registration desk", rotation: 0, widthClass: "w-24", x: 17, y: 20, zone: "Entrance" },
    { id: "corp-3", itemId: "round-table", label: "Networking tables", rotation: 0, widthClass: "w-16", x: 33, y: 58, zone: "Dining area" },
    { id: "corp-4", itemId: "chair", label: "Audience seating", rotation: 0, widthClass: "w-10", x: 56, y: 44, zone: "Guest seating" },
  ],
  reception: [
    { id: "r-1", itemId: "pelamin", label: "Reception pelamin", rotation: 0, widthClass: "w-28", x: 67, y: 18, zone: "Main stage" },
    { id: "r-2", itemId: "round-table", label: "Main dining table", rotation: 0, widthClass: "w-16", x: 30, y: 58, zone: "Dining area" },
    { id: "r-3", itemId: "vip-sofa", label: "VIP family row", rotation: 0, widthClass: "w-24", x: 37, y: 26, zone: "Front seating" },
    { id: "r-4", itemId: "photo-booth", label: "Portrait corner", rotation: 0, widthClass: "w-20", x: 80, y: 58, zone: "Photo corner" },
    { id: "r-5", itemId: "registration", label: "Registration table", rotation: 0, widthClass: "w-24", x: 17, y: 18, zone: "Entrance" },
  ],
};
