insert into public.kd_sutera_kasih_planner_assets (
  planner_item_id,
  label,
  bucket_id,
  collection,
  subtype,
  category,
  note,
  zone_hint,
  shape,
  color,
  width,
  depth,
  height,
  mesh_height,
  icon_name,
  sort_order,
  fallback_model_filename,
  model_rotation_offset,
  model_scale_multiplier,
  is_active
)
values
  ('stage', 'Stage', 'kd_sutera_kasih_planner_assets', 'furniture', 'stage', 'furniture', 'Use this as the focal point for ceremonies, speeches, or pelamin placement.', 'Main stage', 'rectangle', '#cbd5e1', 92, 50, 48, 16, 'square_stack', 10, 'stage.glb', 180, 1.08, true),
  ('round-table', 'Round Table', 'kd_sutera_kasih_planner_assets', 'furniture', 'tables', 'furniture', 'Best for dining zones and group seating throughout the hall.', 'Dining area', 'circle', '#e2e8f0', 40, 40, 40, 24, 'layout_grid', 20, 'round-table-ten-chairs.glb', null, 0.94, true),
  ('round-table-ten', 'Round table 10 pax', 'kd_sutera_kasih_planner_assets', 'furniture', 'tables', 'furniture', 'Round dining table with ten guest chairs.', 'Dining area', 'circle', '#e2e8f0', 40, 40, 40, 24, 'layout_grid', 21, 'round-table-ten-chairs.glb', null, 0.94, true),
  ('round-table-beradab', 'Meja beradab', 'kd_sutera_kasih_planner_assets', 'furniture', 'tables', 'furniture', 'Long beradab table style for family or featured dining.', 'Dining area', 'rectangle', '#d9c2a3', 72, 30, 28, 20, 'layout_grid', 22, 'meja-beradab.glb', 180, 0.92, true),
  ('rect-table', 'Rect Table', 'kd_sutera_kasih_planner_assets', 'furniture', 'tables', 'furniture', 'Useful for buffet lines, registration, or long presentation tables.', 'Service area', 'rectangle', '#e2e8f0', 72, 30, 28, 20, 'layout_grid', 30, 'meja-beradab.glb', 180, 0.92, true),
  ('rect-table-beradab', 'Meja beradab', 'kd_sutera_kasih_planner_assets', 'furniture', 'tables', 'furniture', 'Long table for registration, buffet, or beradab setup.', 'Service area', 'rectangle', '#e2e8f0', 72, 30, 28, 20, 'layout_grid', 31, 'meja-beradab.glb', 180, 0.92, true),
  ('rect-table-service', 'Service table', 'kd_sutera_kasih_planner_assets', 'furniture', 'tables', 'furniture', 'Plain service table footprint for a cleaner operational layout.', 'Service area', 'rectangle', '#d6dee8', 72, 30, 28, 20, 'layout_grid', 32, null, null, null, true),
  ('chair', 'Chair', 'kd_sutera_kasih_planner_assets', 'furniture', 'chairs', 'furniture', 'Adds focused seating near the stage or along the aisle.', 'Guest seating', 'circle', '#94a3b8', 20, 20, 20, 28, 'armchair', 40, 'chair_banquet.glb', 180, 0.85, true),
  ('chair-banquet', 'Banquet chair', 'kd_sutera_kasih_planner_assets', 'furniture', 'chairs', 'furniture', 'Standard banquet chair for guest seating.', 'Guest seating', 'circle', '#94a3b8', 20, 20, 20, 28, 'armchair', 41, 'chair_banquet.glb', 180, 0.85, true),
  ('chair-ornate', 'Ornate armchair', 'kd_sutera_kasih_planner_assets', 'furniture', 'chairs', 'furniture', 'Premium armchair styling for VIP and photo moments.', 'Guest seating', 'rectangle', '#b58ae0', 26, 20, 26, 40, 'armchair', 42, 'chair_ornate-armchair.glb', 180, 0.80, true),
  ('ornate-chair', 'Ornate Chair', 'kd_sutera_kasih_planner_assets', 'furniture', 'chairs', 'furniture', 'A premium accent chair for solemnisation, pelamin styling, or VIP photo moments.', 'Premium seating', 'rectangle', '#b58ae0', 26, 26, 26, 40, 'crown', 50, 'chair_ornate-armchair.glb', 180, 0.80, true),
  ('ornate-chair-gold', 'Ornate armchair', 'kd_sutera_kasih_planner_assets', 'furniture', 'chairs', 'furniture', 'Premium armchair styling for VIP and photo moments.', 'Premium seating', 'rectangle', '#b58ae0', 26, 26, 26, 40, 'crown', 51, 'chair_ornate-armchair.glb', 180, 0.80, true),
  ('ornate-chair-banquet', 'Banquet chair', 'kd_sutera_kasih_planner_assets', 'furniture', 'chairs', 'furniture', 'Simpler banquet chair if the premium chair is not needed.', 'Premium seating', 'circle', '#94a3b8', 20, 26, 20, 28, 'crown', 52, 'chair_banquet.glb', 180, 0.85, true),
  ('vip-sofa', 'VIP Sofa', 'kd_sutera_kasih_planner_assets', 'furniture', 'seating', 'furniture', 'Ideal for family or VVIP seating close to the main focus area.', 'Front seating', 'rectangle', '#f87171', 64, 30, 28, 22, 'sofa', 60, 'chair_loveseat.glb', 180, 1.05, true),
  ('vip-sofa-loveseat', 'Loveseat sofa', 'kd_sutera_kasih_planner_assets', 'furniture', 'seating', 'furniture', 'Loveseat model for VIP and family seating.', 'Front seating', 'rectangle', '#f87171', 64, 30, 28, 22, 'sofa', 61, 'chair_loveseat.glb', 180, 1.05, true),
  ('registration', 'Registration', 'kd_sutera_kasih_planner_assets', 'furniture', 'service', 'furniture', 'Helps define guest arrival and registration flow near the entrance.', 'Entrance', 'rectangle', '#60a5fa', 60, 30, 28, 20, 'ticket', 70, 'meja-beradab.glb', 180, 0.80, true),
  ('registration-desk', 'Registration desk', 'kd_sutera_kasih_planner_assets', 'furniture', 'service', 'furniture', 'Guest check-in desk near the entrance.', 'Entrance', 'rectangle', '#60a5fa', 60, 30, 28, 20, 'ticket', 71, 'meja-beradab.glb', 180, 0.80, true),
  ('registration-counter', 'Counter block', 'kd_sutera_kasih_planner_assets', 'furniture', 'service', 'furniture', 'Simpler counter block for compact setups.', 'Entrance', 'rectangle', '#93c5fd', 60, 30, 28, 20, 'ticket', 72, null, null, null, true),
  ('aisle', 'Aisle Carpet', 'kd_sutera_kasih_planner_assets', 'props', 'floor', 'decor', 'Creates a stronger processional path towards the stage or centre aisle.', 'Centre aisle', 'rectangle', '#ef4444', 24, 140, 120, 1, 'waves', 80, null, null, null, true),
  ('pelamin', 'Pelamin', 'kd_sutera_kasih_planner_assets', 'props', 'wall', 'decor', 'A decorative pelamin focal point for solemnisation and reception backdrops.', 'Main stage', 'rectangle', '#d9c2a3', 74, 62, 36, 56, 'sparkles', 90, 'pelamin_01.glb', 180, 1.08, true),
  ('pelamin-main', 'Classic pelamin', 'kd_sutera_kasih_planner_assets', 'props', 'wall', 'decor', 'Main pelamin backdrop for ceremonies and receptions.', 'Main stage', 'rectangle', '#d9c2a3', 74, 62, 36, 56, 'sparkles', 91, 'pelamin_01.glb', 180, 1.08, true),
  ('pelamin-arch', 'Arch backdrop', 'kd_sutera_kasih_planner_assets', 'props', 'wall', 'decor', 'Arch-style setup that also works for photo corners.', 'Main stage', 'rectangle', '#d9c2a3', 74, 62, 36, 56, 'sparkles', 92, 'pelamin_02.glb', 180, 1.20, true),
  ('floral', 'Floral Stand', 'kd_sutera_kasih_planner_assets', 'props', 'decor', 'decor', 'Works well for framing entrances, stages, and photo corners.', 'Decor points', 'circle', '#34d399', 24, 24, 24, 42, 'flower', 100, 'flower-stand.glb', null, 0.95, true),
  ('photo-booth', 'Photo Booth', 'kd_sutera_kasih_planner_assets', 'props', 'wall', 'decor', 'Reserve a dedicated corner for guest portraits and event photography.', 'Photo corner', 'rectangle', '#c084fc', 50, 44, 44, 58, 'scan_search', 110, 'pelamin_02.glb', 180, 1.20, true),
  ('photo-booth-arch', 'Arch booth', 'kd_sutera_kasih_planner_assets', 'props', 'wall', 'decor', 'Arch-style portrait corner for guest photos.', 'Photo corner', 'rectangle', '#c084fc', 50, 44, 44, 58, 'scan_search', 111, 'pelamin_02.glb', 180, 1.20, true),
  ('photo-booth-pelamin', 'Pelamin booth', 'kd_sutera_kasih_planner_assets', 'props', 'wall', 'decor', 'Pelamin-style backdrop for a stronger photo feature.', 'Photo corner', 'rectangle', '#c084fc', 50, 44, 44, 58, 'scan_search', 112, 'pelamin_01.glb', 180, 1.08, true),
  ('butterfly-companion', 'Butterfly Companion', 'kd_sutera_kasih_planner_assets', 'butterfly_companion', 'butterfly_companion', 'companion', 'A floating butterfly accent that adds soft motion and magical presence around focal spaces.', 'Floating accent', 'circle', '#f0c46c', 14, 14, 14, 14, 'sparkles', 120, 'animated_butterfly.glb', null, 0.80, true),
  ('butterfly-companion-golden', 'Golden butterfly', 'kd_sutera_kasih_planner_assets', 'butterfly_companion', 'butterfly_companion', 'companion', 'Floating butterfly accent with a soft animated silhouette.', 'Floating accent', 'circle', '#f0c46c', 14, 14, 14, 14, 'sparkles', 121, 'animated_butterfly.glb', null, 0.80, true)
on conflict (planner_item_id) do update
set
  label = excluded.label,
  bucket_id = excluded.bucket_id,
  collection = excluded.collection,
  subtype = excluded.subtype,
  category = excluded.category,
  note = excluded.note,
  zone_hint = excluded.zone_hint,
  shape = excluded.shape,
  color = excluded.color,
  width = excluded.width,
  depth = excluded.depth,
  height = excluded.height,
  mesh_height = excluded.mesh_height,
  icon_name = excluded.icon_name,
  sort_order = excluded.sort_order,
  fallback_model_filename = excluded.fallback_model_filename,
  model_rotation_offset = excluded.model_rotation_offset,
  model_scale_multiplier = excluded.model_scale_multiplier,
  is_active = excluded.is_active;

delete from public.kd_sutera_kasih_planner_asset_variants;
