insert into public.kd_sutera_kasih_venues (
  slug,
  name,
  badge_label,
  state,
  address,
  capacity_min,
  capacity_max,
  capacity_label,
  description,
  intro,
  gallery_title,
  contact_email,
  contact_phone,
  operating_hours,
  facilities,
  policies,
  map_embed_url,
  deposit_amount,
  hall_package,
  furniture_package,
  props_package,
  is_active,
  sort_order
)
values
(
  'sutera-kasih-cinta',
  'Sutera Cinta',
  'Premier Venue',
  'Selangor',
  '142 Persiaran Sereni, Shah Alam, Selangor',
  80,
  320,
  '80 - 320 guests',
  'Sutera Cinta is a polished ballroom-style venue in Selangor, designed for elegant receptions, solemn occasions, and milestone celebrations that need a refined yet welcoming atmosphere.',
  'Sutera Cinta balances elegance and comfort for wedding receptions, engagement ceremonies, and intimate milestone events. The hall is especially popular for hosts who want a classic ballroom feeling with smooth guest flow and a polished arrival experience.',
  'Warm reception atmosphere and polished ballroom styling',
  'cinta@suterakasih.example',
  '+60 13-820 1142',
  '9:00 AM - 11:30 PM, Monday through Sunday',
  array[
    'In-house bar service',
    'Professional sound & lighting',
    'Bridal & green rooms',
    'Valet parking',
    'Wheelchair accessible',
    'Climate-controlled hall',
    'On-site coordinator',
    'High-speed Wi-Fi'
  ],
  array[
    'Custom booking times are reviewed again before final confirmation.',
    'Large decor or live performance setups should be noted during booking.',
    'Venue team will advise on layout suitability based on guest count and event type.'
  ],
  'https://www.google.com/maps?q=142%20Persiaran%20Sereni%2C%20Shah%20Alam%2C%20Selangor&output=embed',
  500,
  3200,
  650,
  850,
  true,
  1
),
(
  'sutera-kasih-rindu',
  'Sutera Rindu',
  'Intimate Venue',
  'Johor',
  '28 Jalan Pesisir Mutiara, Johor Bahru, Johor',
  60,
  260,
  '60 - 260 guests',
  'Sutera Rindu brings a softer, more intimate hall experience in Johor, designed for engagement events, family gatherings, and community celebrations that need a warm yet welcoming atmosphere.',
  'Sutera Rindu is suited to events that feel personal and close-knit. It works beautifully for engagement ceremonies, doa selamat gatherings, and smaller receptions where atmosphere and family comfort matter most.',
  'An intimate space for heartfelt gatherings and smaller celebrations',
  'rindu@suterakasih.example',
  '+60 17-441 2035',
  '10:00 AM - 10:30 PM, Monday through Sunday',
  array[
    'In-house bar service',
    'Professional sound & lighting',
    'Bridal & green rooms',
    'Valet parking',
    'Wheelchair accessible',
    'Climate-controlled hall',
    'On-site coordinator',
    'High-speed Wi-Fi'
  ],
  array[
    'Layout planning is recommended for events with more than 180 guests.',
    'Live cooking and heavier vendor load-in should be scheduled in advance.',
    'Final approval depends on the venue calendar and setup requirements.'
  ],
  'https://www.google.com/maps?q=28%20Jalan%20Pesisir%20Mutiara%2C%20Johor%20Bahru%2C%20Johor&output=embed',
  450,
  2600,
  520,
  700,
  true,
  2
),
(
  'sutera-kasih-pesona',
  'Sutera Pesona',
  'Grand Venue',
  'Pulau Pinang',
  '55 Lebuh Seri Bayu, George Town, Pulau Pinang',
  100,
  380,
  '100 - 380 guests',
  'Sutera Pesona offers a brighter, larger-capacity venue in Penang, designed for wedding receptions, annual dinners, and private functions that need a spacious yet polished atmosphere.',
  'Sutera Pesona is designed for events that need more breathing room. From high-guest-count receptions to polished dinner functions, this hall offers stronger capacity support while still feeling warm and premium.',
  'A brighter large-capacity hall for receptions and corporate dinners',
  'pesona@suterakasih.example',
  '+60 12-502 7714',
  '9:00 AM - 11:00 PM, Monday through Sunday',
  array[
    'In-house bar service',
    'Professional sound & lighting',
    'Bridal & green rooms',
    'Valet parking',
    'Wheelchair accessible',
    'Climate-controlled hall',
    'On-site coordinator',
    'High-speed Wi-Fi'
  ],
  array[
    'High-capacity events may require layout approval before confirmation.',
    'Vendor access windows should match the selected booking time range.',
    '3D preview recommendations are most useful for large-scale setups in this hall.'
  ],
  'https://www.google.com/maps?q=55%20Lebuh%20Seri%20Bayu%2C%20George%20Town%2C%20Pulau%20Pinang&output=embed',
  650,
  4200,
  820,
  1100,
  true,
  3
),
(
  'sutera-kasih-bahagia',
  'Sutera Bahagia',
  'Classic Venue',
  'Negeri Sembilan',
  '19 Jalan Taman Damai, Seremban, Negeri Sembilan',
  70,
  280,
  '70 - 280 guests',
  'Sutera Bahagia is a practical and elegant hall in Negeri Sembilan, designed for graduations, family receptions, and private functions that need a flexible yet polished atmosphere.',
  'Sutera Bahagia is a versatile choice when you need a hall that feels polished but still practical. It works especially well for graduations, family functions, and celebrations that need flexible seating and easy movement.',
  'A balanced hall for family events, graduations, and receptions',
  'bahagia@suterakasih.example',
  '+60 14-330 9648',
  '9:30 AM - 11:00 PM, Monday through Sunday',
  array[
    'In-house bar service',
    'Professional sound & lighting',
    'Bridal & green rooms',
    'Valet parking',
    'Wheelchair accessible',
    'Climate-controlled hall',
    'On-site coordinator',
    'High-speed Wi-Fi'
  ],
  array[
    'Graduation and stage-heavy events should indicate AV needs during booking.',
    'The hall supports both banquet and open-floor arrangements.',
    'Final setup suitability is reviewed together with guest count and notes.'
  ],
  'https://www.google.com/maps?q=19%20Jalan%20Taman%20Damai%2C%20Seremban%2C%20Negeri%20Sembilan&output=embed',
  480,
  2900,
  580,
  720,
  true,
  4
),
(
  'sutera-kasih-anggun',
  'Sutera Anggun',
  'Romantic Venue',
  'Melaka',
  '7 Jalan Seri Kenanga, Ayer Keroh, Melaka',
  90,
  300,
  '90 - 300 guests',
  'Sutera Anggun is a polished Melaka venue with a romantic atmosphere, designed for wedding receptions, vow celebrations, and styled evening events that need a graceful yet welcoming setting.',
  'Sutera Anggun leans into a softer and more romantic hall presentation. It suits hosts who want a graceful visual mood for receptions, solemn celebrations, and evening events that feel warm and memorable.',
  'A romantic ballroom atmosphere for elegant evening celebrations',
  'anggun@suterakasih.example',
  '+60 19-288 6401',
  '10:00 AM - 11:30 PM, Monday through Sunday',
  array[
    'In-house bar service',
    'Professional sound & lighting',
    'Bridal & green rooms',
    'Valet parking',
    'Wheelchair accessible',
    'Climate-controlled hall',
    'On-site coordinator',
    'High-speed Wi-Fi'
  ],
  array[
    'Evening ambience setups should be included in the notes section when booking.',
    'Custom planner layouts are encouraged for pelamin-focused events.',
    'Venue review will confirm timing, layout suitability, and staging needs.'
  ],
  'https://www.google.com/maps?q=7%20Jalan%20Seri%20Kenanga%2C%20Ayer%20Keroh%2C%20Melaka&output=embed',
  520,
  3400,
  640,
  900,
  true,
  5
)
on conflict (slug) do update
set
  name = excluded.name,
  badge_label = excluded.badge_label,
  state = excluded.state,
  address = excluded.address,
  capacity_min = excluded.capacity_min,
  capacity_max = excluded.capacity_max,
  capacity_label = excluded.capacity_label,
  description = excluded.description,
  intro = excluded.intro,
  gallery_title = excluded.gallery_title,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  operating_hours = excluded.operating_hours,
  facilities = excluded.facilities,
  policies = excluded.policies,
  map_embed_url = excluded.map_embed_url,
  deposit_amount = excluded.deposit_amount,
  hall_package = excluded.hall_package,
  furniture_package = excluded.furniture_package,
  props_package = excluded.props_package,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;

with media_seed (
  venue_slug,
  media_type,
  storage_path,
  alt_text,
  caption,
  sort_order
) as (
  values
  ('sutera-kasih-cinta', 'hero_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-cinta/hero/engagement.png', 'Sutera Cinta venue hero', 'Premier ballroom atmosphere', 0),
  ('sutera-kasih-rindu', 'hero_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-rindu/hero/birthday.png', 'Sutera Rindu venue hero', 'Intimate hall atmosphere', 0),
  ('sutera-kasih-pesona', 'hero_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-pesona/hero/corporate.png', 'Sutera Pesona venue hero', 'Grand event atmosphere', 0),
  ('sutera-kasih-bahagia', 'hero_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-bahagia/hero/graduation.png', 'Sutera Bahagia venue hero', 'Classic celebration atmosphere', 0),
  ('sutera-kasih-anggun', 'hero_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-anggun/hero/wedding.png', 'Sutera Anggun venue hero', 'Romantic wedding atmosphere', 0),

  ('sutera-kasih-cinta', 'booking_video'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-cinta/booking-video/bg_video.mp4', 'Sutera Cinta booking video', 'Booking page venue preview', 0),
  ('sutera-kasih-rindu', 'booking_video'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-rindu/booking-video/bg_video.mp4', 'Sutera Rindu booking video', 'Booking page venue preview', 0),
  ('sutera-kasih-pesona', 'booking_video'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-pesona/booking-video/bg_video.mp4', 'Sutera Pesona booking video', 'Booking page venue preview', 0),
  ('sutera-kasih-bahagia', 'booking_video'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-bahagia/booking-video/bg_video.mp4', 'Sutera Bahagia booking video', 'Booking page venue preview', 0),
  ('sutera-kasih-anggun', 'booking_video'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-anggun/booking-video/bg_video.mp4', 'Sutera Anggun booking video', 'Booking page venue preview', 0),

  ('sutera-kasih-cinta', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-cinta/gallery/1-Screenshot_1.png', 'Main hall inspiration', 'Grand hall', 1),
  ('sutera-kasih-cinta', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-cinta/gallery/2-Screenshot_10.png', 'Stage and pelamin styling', 'Stage styling', 2),
  ('sutera-kasih-cinta', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-cinta/gallery/3-Screenshot_17.png', 'Reception seating arrangement', 'Reception setup', 3),
  ('sutera-kasih-cinta', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-cinta/gallery/4-Screenshot_21.png', 'Elegant aisle presentation', 'Ceremony mood', 4),

  ('sutera-kasih-rindu', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-rindu/gallery/1-Screenshot_1.png', 'Main hall inspiration', 'Grand hall', 1),
  ('sutera-kasih-rindu', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-rindu/gallery/2-Screenshot_10.png', 'Stage and pelamin styling', 'Stage styling', 2),
  ('sutera-kasih-rindu', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-rindu/gallery/3-Screenshot_17.png', 'Reception seating arrangement', 'Reception setup', 3),
  ('sutera-kasih-rindu', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-rindu/gallery/4-Screenshot_21.png', 'Elegant aisle presentation', 'Ceremony mood', 4),

  ('sutera-kasih-pesona', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-pesona/gallery/1-Screenshot_1.png', 'Main hall inspiration', 'Grand hall', 1),
  ('sutera-kasih-pesona', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-pesona/gallery/2-Screenshot_10.png', 'Stage and pelamin styling', 'Stage styling', 2),
  ('sutera-kasih-pesona', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-pesona/gallery/3-Screenshot_17.png', 'Reception seating arrangement', 'Reception setup', 3),
  ('sutera-kasih-pesona', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-pesona/gallery/4-Screenshot_21.png', 'Elegant aisle presentation', 'Ceremony mood', 4),

  ('sutera-kasih-bahagia', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-bahagia/gallery/1-Screenshot_1.png', 'Main hall inspiration', 'Grand hall', 1),
  ('sutera-kasih-bahagia', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-bahagia/gallery/2-Screenshot_10.png', 'Stage and pelamin styling', 'Stage styling', 2),
  ('sutera-kasih-bahagia', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-bahagia/gallery/3-Screenshot_17.png', 'Reception seating arrangement', 'Reception setup', 3),
  ('sutera-kasih-bahagia', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-bahagia/gallery/4-Screenshot_21.png', 'Elegant aisle presentation', 'Ceremony mood', 4),

  ('sutera-kasih-anggun', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-anggun/gallery/1-Screenshot_1.png', 'Main hall inspiration', 'Grand hall', 1),
  ('sutera-kasih-anggun', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-anggun/gallery/2-Screenshot_10.png', 'Stage and pelamin styling', 'Stage styling', 2),
  ('sutera-kasih-anggun', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-anggun/gallery/3-Screenshot_17.png', 'Reception seating arrangement', 'Reception setup', 3),
  ('sutera-kasih-anggun', 'gallery_image'::public.kd_sutera_kasih_venue_media_type, 'venues/sutera-kasih-anggun/gallery/4-Screenshot_21.png', 'Elegant aisle presentation', 'Ceremony mood', 4)
)
insert into public.kd_sutera_kasih_venue_media (
  venue_id,
  media_type,
  bucket_id,
  storage_path,
  alt_text,
  caption,
  sort_order,
  is_active
)
select
  venue.id,
  media_seed.media_type,
  'kd_sutera_kasih_venue_media',
  media_seed.storage_path,
  media_seed.alt_text,
  media_seed.caption,
  media_seed.sort_order,
  true
from media_seed
join public.kd_sutera_kasih_venues venue on venue.slug = media_seed.venue_slug
on conflict (bucket_id, storage_path) do update
set
  venue_id = excluded.venue_id,
  media_type = excluded.media_type,
  alt_text = excluded.alt_text,
  caption = excluded.caption,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
