insert into public.kd_sutera_kasih_planner_assets (
  planner_item_id,
  label,
  bucket_id,
  collection,
  subtype,
  category,
  note,
  zone_hint,
  shape,
  color,
  width,
  depth,
  height,
  mesh_height,
  icon_name,
  sort_order,
  fallback_model_filename,
  model_storage_path,
  model_public_url,
  model_filename,
  thumbnail_storage_path,
  thumbnail_public_url,
  thumbnail_filename,
  model_rotation_offset,
  model_scale_multiplier,
  is_active
)
select
  variant.variant_id,
  variant.label,
  coalesce(variant.bucket_id, asset.bucket_id, 'kd_sutera_kasih_planner_assets'),
  asset.collection,
  asset.subtype,
  asset.category,
  coalesce(nullif(variant.description, ''), asset.note),
  asset.zone_hint,
  coalesce(variant.shape, asset.shape),
  coalesce(variant.color, asset.color),
  coalesce(variant.width, asset.width),
  coalesce(variant.depth, asset.depth),
  coalesce(variant.height, asset.height),
  coalesce(variant.mesh_height, asset.mesh_height),
  asset.icon_name,
  coalesce(asset.sort_order, 999) + case when coalesce(variant.sort_order, 0) >= 20 then 2 else 1 end,
  coalesce(variant.fallback_model_filename, asset.fallback_model_filename),
  variant.model_storage_path,
  variant.model_public_url,
  variant.model_filename,
  variant.thumbnail_storage_path,
  variant.thumbnail_public_url,
  variant.thumbnail_filename,
  coalesce(variant.model_rotation_offset, asset.model_rotation_offset),
  coalesce(variant.model_scale_multiplier, asset.model_scale_multiplier),
  variant.is_active
from public.kd_sutera_kasih_planner_asset_variants variant
inner join public.kd_sutera_kasih_planner_assets asset
  on asset.planner_item_id = variant.planner_item_id
on conflict (planner_item_id) do update
set
  label = excluded.label,
  bucket_id = excluded.bucket_id,
  collection = excluded.collection,
  subtype = excluded.subtype,
  category = excluded.category,
  note = excluded.note,
  zone_hint = excluded.zone_hint,
  shape = excluded.shape,
  color = excluded.color,
  width = excluded.width,
  depth = excluded.depth,
  height = excluded.height,
  mesh_height = excluded.mesh_height,
  icon_name = excluded.icon_name,
  sort_order = excluded.sort_order,
  fallback_model_filename = excluded.fallback_model_filename,
  model_storage_path = excluded.model_storage_path,
  model_public_url = excluded.model_public_url,
  model_filename = excluded.model_filename,
  thumbnail_storage_path = excluded.thumbnail_storage_path,
  thumbnail_public_url = excluded.thumbnail_public_url,
  thumbnail_filename = excluded.thumbnail_filename,
  model_rotation_offset = excluded.model_rotation_offset,
  model_scale_multiplier = excluded.model_scale_multiplier,
  is_active = excluded.is_active;

delete from public.kd_sutera_kasih_planner_asset_variants;

comment on table public.kd_sutera_kasih_planner_asset_variants is
  'Deprecated. Planner variants were promoted into planner assets on 2026-04-26.';
